version: '3'
services: 
  node-server:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app/
    restart: always
    ports:
      - "8080:8080"
  mongo-server:
    image: mongo
    ports: 
      - 27017:27017